### ISSUE TITLE
Playlist problem

### ISSUE THREAD

**Issue by sylvainar** [Polochon-street/leleleplayer#3]
First, a button "Clear playlist" should be a good thing.

I discovered a problem : while trying to remove every title in the playlist one by one, the software crashed when removing the last one..

**Comment by sylvainar** [comment]
It will be nice if we can select multiple songs with Ctrl or Shift.

**Comment by Polochon-street** [comment]
First issue fixed in commit e61a6af1e7a29e4eff806fc13b8c5cfbf695b76d.
Playlist selection will be improved in next commit.
Thanks for the feedback! :)
