### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by sylvainar** [Polochon-street/leleleplayer#5]
An icon is missing, we got a Windows default one instead.

![](http://puu.sh/lf6TC/9f2d0d699f.png)

Strange, because the uninstall icon is there.

**Comment by sylvainar** [comment]
And in the taskbar too
![](http://puu.sh/lf6Vi/f80c20d7d8.jpg)

**Comment by Polochon-street** [comment]
Ninja-fixed in the [latest](https://github.com/Polochon-street/leleleplayer/releases/tag/v0.1.2) release!
