### ISSUE TITLE
No import progress in the GUI

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/leleleplayer#8]
Hi,

It would be really cool to have a progress bar in the UI, especially when doing a large import (± 100GB in my case). Plus, some files had errors (red errors in the console), but due to the amount of logs in the console, I missed them. Would be really useful to have a summary of the import at the end.

Thanks!

**Comment by Polochon-street** [comment]
Hi!
I used a label in the bottom-right corner in the [last](https://github.com/Polochon-street/leleleplayer/commit/deb0a78a58612b17a9708da1ea2367eb58a50952) commit to indicate progress (in a i/n form); previous versions used a progressbar, but it was a bit clumsy. What do you think? 

For the logs, ffmpeg displays its errors in red, and they are often nonfatal, so no need to worry; I'll had a logging system when I have more time.

Thanks for the feedback!

**Comment by Phyks** [comment]
Hmm, I updated the AUR package on my install, but did not see any difference, maybe I missed it. Do you have a screenshot please? :)

**Comment by Polochon-street** [comment]
Try the AUR package again? It seems to work here :)
![2015-11-16-211736_1354x733_scrot](https://cloud.githubusercontent.com/assets/9823290/11193541/7f3d032a-8ca7-11e5-9d25-5d934d776b11.png)

**Comment by Phyks** [comment]
Ok, I did not have it, it's ok for me :) Thanks!
