### ISSUE TITLE
Make it a separate standalone library and a GUI?

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/leleleplayer#9]
Hi,

I am really interested in Leleleplayer, especially since I have been looking for a similar player for a while, and finally ended up using Grooveshark to listen the same songs I had on my computer, just for its ability to make mixes =(

However, I am not a huge fan of the actual GUI, especially since moving to a new GUI means changing habits and having to deal with missing functionnalities that we are used to.

As looking in the repo, GUI is quite easy to remove from it. But, why not splitting it in two repos, one with a standalone library only, and one with the GUI only?

I think this would ease use of the library in third party apps such as plugins for Rhythmbox or Ampache.

Thanks

**Comment by Polochon-street** [comment]
Hi!

Following your advice, I created a standalone library that I called bliss; the repo is [here](https://github.com/Polochon-street/bliss), I made the initial commit minutes ago so it may be highly unstable (more than my player). I will soon make leleleplayer use bliss, but for now, bliss stands alone.

Hope it works!

**Comment by Phyks** [comment]
Really cool! Thanks! Will try to find something to have a deeper look at it and write Python bindings :)

**Comment by fossfreedom** [comment]
@Polochon-street - looks very interesting - thanks for making this a separate library.

@Phyks - if  you can write the python bindings I would be interested in helping writing a rhythmbox plugin.
